dependencies:
 - smartcontractkit/chainlink-brownie-contracts@1.1.1
 - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0'
dotenv: .env
networks:
  default: development
  development:
    keyHash: '0x0476f9a745b61ea5c0ab224d3a6e4c99f0b02fce4da01143a4f70aa80ae76e8a'
    fee: 100000000000000000
    verify: False
  goerli:
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    vrf_coordinator: '0x2bce784e69d2Ff36c71edcB9F88358dB0DfB55b4'
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    keyHash: '0x0476f9a745b61ea5c0ab224d3a6e4c99f0b02fce4da01143a4f70aa80ae76e8a'
    fee: 100000000000000000
    verify: True  
  sepolia:
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: False
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4ec3df9cbd43714fe2740f5e3616155c5b8419'
    verify: False
  ganache_gui:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}